apiVersion: v1
kind: ConfigMap
metadata:
  name: fn-config
data:
  MQ_URL: redis://redis-master.default
  DB_URL: postgres://postgres:postgres@postgresql-master.default/?sslmode=disable
---
kind: Service
apiVersion: v1
metadata:
  name: fn-service
  labels:
    app: fn
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: fn
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-api-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: fn
    spec:
      terminationGracePeriodSeconds: 1
      imagePullSecrets:
      - name: sre-reg-secret
      containers:
      - name: fn-api
        image:  registry.oracledx.com/skeppare/functions:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: MQ_URL
          valueFrom:
            configMapKeyRef:
              name: fn-config
              key: MQ_URL
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: fn-config
              key: DB_URL
        volumeMounts:
        - name: docker-socket
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: docker-socket
        hostPath:
          path: "/var/run/docker.sock"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-ui-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fn
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: fn-ui
        image: iron/functions-ui:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: "http://127.0.0.1:8080"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-master
  labels:
    app: postgresql
    role: datastore
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
    role: datastore
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgresql-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
        role: datastore
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: fn-postgresql
        image: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: mq
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: mq
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: mq
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: fn-redis
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Secret
metadata:
  name: sre-reg-secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJyZWdpc3RyeS5vcmFjbGVkeC5jb20iOnsidXNlcm5hbWUiOiJhZ2VudCIsInBhc3N3b3JkIjoiZ2YyMVx1MDAyNjU0RyIsImVtYWlsIjoiICIsImF1dGgiOiJZV2RsYm5RNloyWXlNU1kxTkVjPSJ9fQ==
