piVersion: v1
kind: ConfigMap
metadata:
  name: fn-service-config
  namespace: default
data:
  MQ_URL: redis://fn-redis-master.default
  DB_URL: mysql://root:boomsauce@tcp(fn-mysql-master:3306)/fn
  ZIPKIN_URL: http://zipkin:9411/api/v1/spans
  API_URL: http://fn-service:8080
---
apiVersion: v1
kind: Service
metadata:
  name: fn-service
  labels:
    app: fn
    role: fn-service
spec:
  type: LoadBalancer
  ports:
  - name: fn-service
    port: 8080
    targetPort: 8080
  - name: fn-ui
    port: 80
    targetPort: 80
  selector:
    app: fn
    role: fn-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fn
        role: fn-service
    spec:
      terminationGracePeriodSeconds: 1
      imagePullSecrets:
      - name: docker-reg-secret
      - name: sre-reg-secret
      containers:
      - name: fn-service
        image: registry.oracledx.com/skeppare/functions-service:0.1.46
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: MQ_URL
          valueFrom:
            configMapKeyRef:
              name: fn-service-config
              key: MQ_URL
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: fn-service-config
              key: DB_URL
        - name: ZIPKIN_URL
          valueFrom:
            configMapKeyRef:
              name: fn-service-config
              key: ZIPKIN_URL
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      - name: fn-ui
        image: registry.oracledx.com/skeppare/functions-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: fn-service-config
              key: API_URL
      - name: statsd-exporter
        image: registry.oracledx.com/odxsre/core-services-statsd-exporter:latest
        imagePullPolicy: IfNotPresent
      - name: prometheus-pusher
        image: registry.oracledx.com/odxsre/core-services-prometheus-pusher:latest
        imagePullPolicy: IfNotPresent
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: fn-mysql-master
  labels:
    app: mysql
    role: datastore
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
    role: datastore
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-mysql-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        role: datastore
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: fn-mysql
        image: mysql:5.7
        args:
          - "--max-connections=500"
          - "--wait-timeout=300"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: boomsauce
        - name: MYSQL_DATABASE
          value: fn
---
apiVersion: v1
kind: Service
metadata:
  name: fn-redis-master
  labels:
    app: redis
    role: mq
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: mq
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fn-redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: mq
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: fn-redis
        image: redis:4.0
        ports:
        - containerPort: 6379
